version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
    ports:
      - 3000:3000
    command:  bash -c "rm -f tmp/pids/server.pid; rails s -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
